### ISSUE TITLE
US 01 – SetUp Repository

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#1]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge,  reference projects  and also can get into contact.

## Value proposition

**As a** **web developer**
**I want to** **implement the chosen tech stack initially**
**so that** **I can start working on my personal website repository**  

## Acceptance criteria

- [ ] the initial tech stack includes the technical solution to start with an react App with an Next.js framework.
- [ ] the website is based as mobile first App.

## Description / Ressources

![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/0c7bb328-775f-4726-998e-6761022c6406)

## Tasks / Technical Solution

- [ ] Initialize the repository `personal-website` locally and on GitHub `https://github.com/miriam-ertl/personal-website`.
- [ ] the repository should work with the following tech stack. Therefore the dependecies are installed in the repository:
    - [ ] React
    - [ ] Next.js
    - [ ] JavaScript
    - [ ] Typescript
    - [ ] Tailwind
    - [ ] Husky
