### ISSUE TITLE
US 01 – SetUp Repository

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#1]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** webdeveloper
**I want to** define the tech stack
**so that** t can set up the repository

## Acceptance criteria

- [ ] the name of the repository is defined 
- [ ] the tech stack is defined
- [ ] the tech stack is approved by Marcel

## Description / Ressources

[Excalidraw]((https://excalidraw.com/#json=j2iuKSq5-MpEJlelXEFQq,cMZRAZN8AGM91hnwYL7ARA))

![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/502b69b5-9d40-4ced-b3ae-cd23f4e4c834)

## Tasks / Technical Solution

- [ ] Create a new repository with next.js locally and remote on GitHub
