### ISSUE TITLE
US 7 – Homepage Footer

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#11]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** web developer
**I want to** define the footer elements
**so that** it is possible to provide social and legal links.

## Acceptance criteria

- [ ] the footer contains: 
    - [ ]  social media icons
    - [ ]  a icon to write a mail
    - [ ]  the legal informations

## Description / Ressources

[Personal Website, Figma: Homepage-Design](https://www.figma.com/file/z9SNhqc3eW6BBYQGWkavR1/PersWebs?type=design&node-id=1%3A2&mode=design&t=Um0dnbyH5SiCQGab-1)

## Tasks / Technical Solution

- [ ] Create a branch
- [ ]  adjust a flexbox system within the Footer
- [ ] create a Footer component including:
     - [ ]  a list of icons (which will include href-links later): LinkedIn, GitHub, Email 
     - [ ]  a text element (which will link to a disclaimer)
     - [ ]  a text element (which will link to a impressum)
     
Links will work later, when additional sites are setup.
