### ISSUE TITLE
US 10 – unitTest

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#12]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** webdeveloper
**I want to** write a test
**so that** I can see ...

## Acceptance criteria

- [ ] the first test in next/jest for a page is working

## Description / Ressources

[Setting up Jest with Next.js](https://nextjs.org/docs/app/building-your-application/testing/jest#creating-your-first-test)

## Tasks / Technical Solution

- [ ] create a branch
- [ ]  create a folder  for `__tests__` 
- [ ]  create a file with `index.test.jsx`
- [ ] use the next/Jest example of  the docs to run the first test on Homepage
- [ ] optionally, a snapshot test is added
