### ISSUE TITLE
US 6 – Hompage Navigation

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#13]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** user
**I want to** have a mobile navigation
**so that** I can visit an about page

## Acceptance criteria

- [ ] there is a button which opens a mobile menu
- [ ] in the opened menu I see an link to `About` and an `X`-button
- [ ] clicking on the `X`-button the opened menu closes automatically
- [ ] clicking on the `About` will lead to a subpage

## Description / Ressources

[Personal Website, Figma: Homepage-Design](https://www.figma.com/file/z9SNhqc3eW6BBYQGWkavR1/PersWebs?type=design&node-id=1%3A2&mode=design&t=Um0dnbyH5SiCQGab-1)

## Tasks / Technical Solution

- [ ] Create a branch
- [ ] adjust a flexbox system within the mobile menu for the opened menu
- [ ] create a Navigation component with states including:
     - [ ]  a list for the links which link to the pages
     - [ ]  a button with the x icon which closes the opened menu as
          
The link will lead to a blank About page.
