### ISSUE TITLE
US 02  – Planning Project Steps

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#2]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** webdeveloper
**I want to** define the single process steps
**so that** I have an overview obout the features to be developed

## Acceptance criteria

- [ ] plan with the major project steps considers the homepage, work, about and contact page
- [ ] the plan considers the different disciplines:
     - [ ]  mockup in Figma
     - [ ]  developing the features
     - [ ]  writing tests for the features
     - [ ]  deployment

## Description / Ressources

[Project Plan](https://miro.com/app/board/uXjVN7LpDX4=/?share_link_id=618846654724)

![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/ad552507-022e-4fb0-bb76-1e37a7ae14d5)

## Tasks / Technical Solution

- [ ] create a MiroBoard
- [ ] define the single tasks according to the estimated release product, a personal website
- [ ] set a timing according to the single tasks
