### ISSUE TITLE
US 02  – Planning Project Steps

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#2]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** **web developer**
**I want to** **an project plan**
**so that** **I can plan the single steps for the features**  

## Acceptance criteria

- [ ] the plan has to visualize all needed steps to achive the MVP
- [ ] the plan has to be approved by Marcel
    

## Description / Ressources

![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/d3eefbdd-2042-4273-948b-2da61e8c5ff7)

## Tasks / Technical Solution

- [ ] set up a plan with the days till end of February 2024
- [ ] structure the projects’ features with milestones for the following topics:
    - [ ] Figma design
    - [ ] Coding
    - [ ] Testing
    - [ ] Connect with Domain
