### ISSUE TITLE
US 03 - Mobile First / Figma Design

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#3]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** webdesigner
**I want to** create an attractive mock up
**so that**  users will get a good first impression of the person.

## Acceptance criteria

- [ ] the typefonts, colors and the buttons are defined for the unique appearance
- [ ] the design is created for mobile first
- [ ] the design of the homepage shows areas for:
     - [ ] the logo
     - [ ] the navigation 
     - [ ] the introduction text which has a link to the about page
     - [ ] an inspirational image
     - [ ] a text about the profession
     - [ ] an area with teaser which represent the work
     - [ ] the footer which provides contact possibilities and social links
     - [ ] the leagl information

## Description / Ressources

[Personal Website, Figma: Basic Design Elements](https://www.figma.com/file/z9SNhqc3eW6BBYQGWkavR1/PersWebs?type=design&node-id=5%3A2&mode=design&t=wVYHj0W81wF7xNjx-1)

![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/39654f35-3da6-4af2-b124-2ac5883cac0e)
![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/4eecfe87-b5e3-4e2d-afab-72126b723258)
![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/5c786840-f5ae-4b35-9869-2a3cc581ea1d)

[Personal Website, Figma: Homepage-Design](https://www.figma.com/file/Ya8edryKWLhRt5WvppReZ0/PersWebs?type=design&node-id=0%3A1&mode=design&t=mZm3FmjXug1OdPwf-1

## Tasks / Technical Solution

- [ ] create a Figma design file with
     - [ ] design basics for the typography, colors, buttons
- [ ] design a mock up in Figma for the homepage including
     - [ ] the header with the navigation
     - [ ] the body with three different sections: introduction, main text field, overview over the skills and references
     - [ ] the footer with the links to profiles on LinkedIn, GitHub, opens a mailto window and the impressum and Datenschutz
- [ ] the design works on IPhone SE
- [ ] the main language is German
