### ISSUE TITLE
US 03 - Mobile First / Figma Design

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#3]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** user
**I want to** have a well designed mobile website
**so that** I navigate to the needed information easily

## Acceptance criteria

- [ ] the basic design elements are defined
- [ ] the basic design elements are implemented on the first page: mobile homepage for the personal website

## Description / Ressources

[Figma Design](https://www.figma.com/file/z9SNhqc3eW6BBYQGWkavR1/PersWebs?type=design&node-id=5%3A2&mode=design&t=wVYHj0W81wF7xNjx-1)

## Tasks / Technical Solution

- [ ] open an Figma file with pages to introduce the design
- [ ] define basic design elements like: Typography, Colours, Buttons
     - [ ] export properties
- [ ] design the homepage including a header, body with the main section and a footer
     - [ ] work with a grid
     - [ ] mobile first standard should be working for iPhone SE
