### ISSUE TITLE
US 04 – Basic style elements

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#4]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** webdeveloper
**I want to** define the basic css
**so that** the site elements can be styled  

## Acceptance criteria

- [ ] the typography system is defined and ready to use
- [ ] all needed colors are defined and ready to use
- [ ] the main buttons – primary, secondary – are defined and ready to use

## Description / Ressources

[Personal Website, Figma: Basic Design Elements](https://www.figma.com/file/z9SNhqc3eW6BBYQGWkavR1/PersWebs?type=design&node-id=5%3A2&mode=design&t=wVYHj0W81wF7xNjx-1)

![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/29d0717b-71a2-46dc-8f80-6fd81b5c4664)
![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/f6e68b78-70bd-4dfe-963e-cd986bf91998)
![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/1ceb5ffa-fb06-4f17-b1cf-09c7a4295025)

[Personal Website, Figma: Homepage-Design](https://www.figma.com/file/z9SNhqc3eW6BBYQGWkavR1/PersWebs?type=design&node-id=1%3A2&mode=design&t=Um0dnbyH5SiCQGab-1)

## Tasks / Technical Solution

- [ ] Create a branch
- [ ] define basic design elements in repository: 
    - [ ] Typography: H1 - H4 etc., 
    - [ ] Colours, 
    - [ ] Buttons: primary, secondary as Components
