### ISSUE TITLE
US 04 – Basic style elements

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#4]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** webdeveloper
**I want to** define the basic css
**so that** the site elements can be styled  

## Acceptance criteria

- [ ] the typography system is defined and ready to use
- [ ] all needed colors are defined and ready to use
- [ ] the main buttons – primary, secondary – are defined and ready to use

## Description / Ressources

[Personal Website, Figma: Basic Design Elements](https://www.figma.com/file/z9SNhqc3eW6BBYQGWkavR1/PersWebs?type=design&node-id=5%3A2&mode=design&t=wVYHj0W81wF7xNjx-1)

![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/c97b3005-daec-4603-8390-1e1bef772cf1)
![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/6d67b909-63b7-42b6-b8dd-7fbfda042069)
![Image](https://github.com/miriam-ertl/personal-website/assets/139959429/3b40f77b-5769-4b71-b7ae-26aca41fa75d)

[Personal Website, Figma: Homepage-Design](https://www.figma.com/file/z9SNhqc3eW6BBYQGWkavR1/PersWebs?type=design&node-id=1%3A2&mode=design&t=Um0dnbyH5SiCQGab-1)

## Tasks / Technical Solution

- [ ] create a feature branch
- [ ] define basic design elements in repository: 
    - [ ] Typography: H1 - H4 etc., 
    - [ ] Colours
- [ ] develop the basic buttons as styled components with the Figma properties 
    - [ ] primary & secondary Button
