### ISSUE TITLE
US 5 – Homepage Body

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#6]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** web developer
**I want to** define the body elements
**so that** a first look&feel is grapsable.

## Acceptance criteria

- [x] the body contains different sections with:
    - [x]  an introduction with inspirational text and an image as an eyecatcher with a link to the about page
    - [x]  an introduction text 
    - [x]  references, images with a link to a page with skills/references information 

## Description / Ressources

[Personal Website, Figma: Homepage-Design](https://www.figma.com/file/z9SNhqc3eW6BBYQGWkavR1/PersWebs?type=design&node-id=1%3A2&mode=design&t=Um0dnbyH5SiCQGab-1)

## Tasks / Technical Solution

- [x] Create a branch
- [x] define a maximum width for the layout (mobile first)
- [x] define basic layout with modern normalize.css
- [x] adjust a grid system for the Header, Content, Footer
- [ ] develop structure with semantic HTML elements in the content 
- [ ] create elements for:
     - [ ]  text elements
     - [ ]  images 
     - [ ]  image overview
     
Links will work later, when additional sites are setup.
