### ISSUE TITLE
US 8 – Homepage Header

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#7]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** web developer
**I want to** define the header
**so that** the layout contains this basic element 

## Acceptance criteria

- [ ] the header contains: 
    - [ ]  the logo
    - [ ]  a keyword about the profession 

## Description / Ressources

[Personal Website, Figma: Homepage-Design](https://www.figma.com/file/cLC7Mt6zJt99ykPT0mjIZV/PersWebs?type=design&node-id=0%3A1&mode=design&t=JFWxBpCJgVeEumpL-1)

## Tasks / Technical Solution

- [ ] Create a branch
- [ ]  adjust a felxbox within the Header
- [ ] develop structure with semantic HTML elements
- [ ] create a Header component including:
     - [ ]  a logo (.svg)
     - [ ]  a small text element
     - [ ]  a placeholder for the navigation
     
Links will work later, when additional sites are setup.
