### ISSUE TITLE
US 9 – SetUp-unitTest

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/personal-website#8]
## Context
The MVP is a personal website for Miriam Ertl focused on the profession as a web developer on junior level. The user can inform itself about current skills, knowledge, reference projects  and also can get into contact.

## Value proposition

**As a** webdeveloper
**I want to** setup jest
**so that** I can carry out unit tests.

## Acceptance criteria

- [ ] the needed file structure for unit tests is set up
- [ ] the dependencies are installed
- [ ] scripts are running 

## Description / Ressources

[Setting up Jest with Next.js](https://nextjs.org/docs/app/building-your-application/testing/jest)

## Tasks / Technical Solution

- [ ] Create a branch
- [ ] install Jest manually
- [ ] generate basic Jest configuration
- [ ] configure `jest.config.ts`
- [ ] extend  Jest with custom matchers
- [ ] create file `jest.setup.ts` to import testing-library
- [ ] add scripts for `test:watch` and `test:coverage`
